# # see: https://terraform-docs.io/user-guide/configuration/version
version: ">= 0.13.0, < 1.0.0"

# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table
#markdown table
#md doc

# see: https://terraform-docs.io/user-guide/configuration/recursive
recursive:
  enabled: true
  path: modules

# see: https://terraform-docs.io/user-guide/configuration/header-from
#header-from: "docs/header.md"

# see: https://terraform-docs.io/user-guide/configuration/footer-from
#footer-from: "docs/footer.md"

# see: https://terraform-docs.io/user-guide/configuration/sections
sections:
  show:
    - requirements
    - resources 
    - inputs
    - outputs
    - providers
    - modules
    - data-sources 

content: |-

  {{ .Requirements }}

  #### Resources
  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

# see: https://terraform-docs.io/user-guide/configuration/output
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->

    {{ .Content }}

    <!-- END_TF_DOCS -->

# see: https://terraform-docs.io/user-guide/configuration/sort
sort:
  enabled: true
  by: required

# https://terraform-docs.io/user-guide/configuration/output-values/
output-values:
  enabled: false
  from: ""

# see: https://terraform-docs.io/user-guide/configuration/settings
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 4
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true